// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import { analyzeProducts } from "@/lib/gads-product-simulation";
import ProfitabilitySimulator from "./ProfitabilitySimulator";

const analysis = analyzeProducts([
  { productId: "loss", title: "Loss product", cost: 1200, conversionValue: 600, conversions: 2, clicks: 500, impressions: 5000 },
  { productId: "winner", title: "Profitable product", cost: 240, conversionValue: 2400, conversions: 8, clicks: 120, impressions: 1200 },
], { breakEvenRoas: 5, months: 12 });
const snapshot = {
  website: "https://example.com",
  accountName: "Example",
  averageOrderValue: 300,
  goodsCost: 180,
  breakEvenCpa: 60,
  breakEvenRoas: 5,
  current: { spend: 120, revenue: 600, orders: 2, cpa: 60, roas: 5 },
  optimized: { spend: 120, revenue: 900, orders: 3, cpa: 40, roas: 7.5 },
  losses: [],
  opportunities: [],
  campaigns: [
    { name: "PMax All Products", channel: "PERFORMANCE_MAX", spend: 900, revenue: 2700, roas: 3, status: "ENABLED" },
    { name: "Search Generic", channel: "SEARCH", spend: 100, revenue: 200, roas: 2, status: "ENABLED" },
  ],
};

afterEach(cleanup);

const renderSimulator = () => render(
  <ProfitabilitySimulator
    analysis={analysis}
    averageOrderValue={300}
    snapshot={snapshot}
    currencyCode="EUR"
  />,
);

describe("profitability report simulator", () => {
  it("renders the original report concept as one ordered report shell", () => {
    const { container } = renderSimulator();

    expect(container.querySelector('[data-report-concept="original"]')).toBeTruthy();
    expect(screen.getByText("Your account generates sales, but budget reaches the wrong products.")).toBeTruthy();
    expect(screen.getByText("Decision summary")).toBeTruthy();
    expect(screen.getByText(/You pay €60 for an order that can support at most €60/)).toBeTruthy();
    expect(screen.getByText("Recover budget trapped in the wrong products.")).toBeTruthy();

    const rendered = container.textContent ?? "";
    expect(rendered.indexOf("Decision summary")).toBeLessThan(rendered.indexOf("Priority 1 · Stop losses"));
    expect(rendered.indexOf("Priority 1 · Stop losses")).toBeLessThan(rendered.indexOf("Priority 2 · Recover growth"));
    expect(rendered.indexOf("Priority 2 · Recover growth")).toBeLessThan(rendered.indexOf("Interactive simulation · optimized account"));
    expect(rendered.indexOf("Interactive simulation · optimized account")).toBeLessThan(rendered.indexOf("Scenario, not a promise"));
  });

  it("shows measured before data and a structurally matching simulated after table", () => {
    renderSimulator();
    expect(screen.getByRole("region", { name: "Account profitability comparison" })).toBeTruthy();
    expect(screen.getByText("How the account could look after optimization")).toBeTruthy();
    expect(screen.getByText("Current account")).toBeTruthy();
    expect(screen.getAllByText("Optimized + CSS").length).toBeGreaterThan(0);
    expect(screen.getByText("Priority 1 · Stop losses")).toBeTruthy();
    expect(screen.getByText("Priority 2 · Recover growth")).toBeTruthy();
    expect(screen.getAllByText((_, element) => element?.classList.contains("source") === true && element.textContent === "Measured from Google Ads · last 12 months")).toHaveLength(2);
    expect(screen.getAllByText("Future simulation")).toHaveLength(2);
    expect(screen.getByText("Before: measured products → After: optimized promotion")).toBeTruthy();
    expect(screen.getByText("Estimated sales generated by the profitable products below")).toBeTruthy();
    expect(screen.getAllByText("Product").length).toBeGreaterThanOrEqual(3);
    for (const heading of ["Clicks", "Cost", "Orders", "CPA", "Sales", "ROAS"]) {
      expect(screen.getAllByText(heading).length).toBeGreaterThanOrEqual(3);
    }
    expect(screen.queryByText("Profit after advertising")).toBeNull();
  });

  it("starts at measured monthly spend and updates the after table to zero", () => {
    renderSimulator();
    const slider = screen.getByRole("slider", { name: "Simulated monthly budget" }) as HTMLInputElement;
    expect(Number(slider.value)).toBe(Math.round(analysis.currentMonthlySpend));
    expect(slider.min).toBe("0");
    expect(Number(slider.max)).toBe(analysis.economicBudgetLimit);

    fireEvent.change(slider, { target: { value: "0" } });
    expect(screen.getByTestId("expected-revenue").textContent).toContain("€0");
    expect(screen.getByTestId("expected-orders").textContent).toContain("0");
    expect(screen.getByTestId("expected-roas").textContent).toContain("—");
  });

  it("switches the scenario summary between measured and optimized values", () => {
    renderSimulator();

    expect(screen.getByTestId("scenario-outcome").textContent).toContain("8× ROAS");
    fireEvent.click(screen.getByRole("tab", { name: "Current account" }));
    expect(screen.getByTestId("scenario-outcome").textContent).toContain("5× ROAS");
    expect(screen.getByRole("tab", { name: "Current account" }).getAttribute("aria-selected")).toBe("true");

    fireEvent.click(screen.getByRole("tab", { name: "Optimized + CSS" }));
    expect(screen.getByTestId("scenario-outcome").textContent).toContain("8× ROAS");
    expect(screen.getByRole("tab", { name: "Optimized + CSS" }).getAttribute("aria-selected")).toBe("true");
  });

  it("shows orders, CPA and ROAS as whole numbers throughout the interactive report", () => {
    const { container } = renderSimulator();
    expect(screen.queryByText(/^\d+[,.]\d+×$/)).toBeNull();
    expect(container.textContent).not.toContain("€40.00");
    expect(container.textContent).toContain("€40");
  });

  it("explains the exact three-step strategy and the CSS assumption", () => {
    renderSimulator();
    expect(screen.getByText("1 · Stop losses")).toBeTruthy();
    expect(screen.getByText("2 · Move budget")).toBeTruthy();
    expect(screen.getByText("3 · Scale carefully")).toBeTruthy();
    expect(screen.getAllByText(/estimated 20% CPC reduction/i)).toHaveLength(2);
  });

  it("compares the measured campaign structure with the recommended ecommerce architecture", () => {
    renderSimulator();

    expect(screen.getByRole("region", { name: "Recommended campaign structure" })).toBeTruthy();
    expect(screen.getByText("How campaigns are organized now")).toBeTruthy();
    expect(screen.getByText("PMax All Products")).toBeTruthy();
    expect(screen.getByText("Search Generic")).toBeTruthy();
    expect(screen.getByText("How the account should be organized")).toBeTruthy();
    expect(screen.getByText("Search · brand protection")).toBeTruthy();
    expect(screen.getByText("Performance Max · profitable products")).toBeTruthy();
    expect(screen.getByText("Standard Shopping · control")).toBeTruthy();
    expect(screen.getByText("Measured from Google Ads · last 30 days")).toBeTruthy();
    expect(screen.getByText("Devrika recommendation")).toBeTruthy();
  });

  it("renders a wide report surface instead of the narrow legacy report", () => {
    const { container } = renderSimulator();
    expect(container.firstElementChild?.getAttribute("data-profitability-layout")).toBe("wide-v1");
  });

  it("limits every visible product table to ten compact rows without changing the analyzed population", () => {
    const losses = Array.from({ length: 12 }, (_, index) => ({
      ...analysis.losses[0],
      productId: `loss-${index}`,
      title: `Loss product ${index}`,
      monthlyCost: 1200 - index,
    }));
    const opportunities = Array.from({ length: 12 }, (_, index) => ({
      ...analysis.opportunities[0],
      productId: `winner-${index}`,
      title: `Profitable product ${index}`,
      estimatedSalesOpportunity: 2400 - index,
    }));
    const expandedAnalysis = { ...analysis, losses, opportunities };

    render(<ProfitabilitySimulator analysis={expandedAnalysis} averageOrderValue={300} snapshot={snapshot} currencyCode="EUR" />);

    expect(screen.getByRole("table", { name: "Products consuming your budget" }).querySelectorAll("tbody tr")).toHaveLength(10);
    expect(screen.getByRole("table", { name: "Profitable products receiving too little traffic" }).querySelectorAll("tbody tr")).toHaveLength(10);
    expect(screen.getByRole("table", { name: "Optimized product promotion" }).querySelectorAll("tbody tr")).toHaveLength(10);
    expect(expandedAnalysis.losses).toHaveLength(12);
    expect(expandedAnalysis.opportunities).toHaveLength(12);
  });

  it("shows one consistent twelve-month evidence window in the measured product tables", () => {
    renderSimulator();

    const lossRow = screen.getByRole("table", { name: "Products consuming your budget" }).querySelector("tbody tr");
    const opportunityRow = screen.getByRole("table", { name: "Profitable products receiving too little traffic" }).querySelector("tbody tr");

    expect(lossRow?.textContent).toContain("€1,200");
    expect(lossRow?.textContent).toContain("2");
    expect(lossRow?.textContent).toContain("€600");
    expect(lossRow?.textContent).toContain("−€1,080");
    expect(opportunityRow?.textContent).toContain("€240");
    expect(opportunityRow?.textContent).toContain("8");
    expect(opportunityRow?.textContent).toContain("€2,400");
    expect(screen.getAllByText((_, element) => element?.classList.contains("source") === true && element.textContent === "Measured from Google Ads · last 12 months")).toHaveLength(2);
  });
});
